services:
  osrm:
    image: osrm/osrm-backend
    volumes:
      - ~/singapore-osm:/data
      - ./profiles:/profiles
    networks:
      - default
    ports:
      - 6000:5000
    restart: unless-stopped
    command: >
      bash -c "
      osrm-extract -p /profiles/foot.lua /data/singapore-latest.osm.pbf && 
      osrm-partition /data/singapore-latest.osrm && 
      osrm-customize /data/singapore-latest.osrm && 
      osrm-routed \
      --algorithm mld \
      --max-matching-size 20000 \
      --max-viaroute-size 20000 \
      --max-trip-size 20000 \
      --max-table-size 20000 \
      /data/singapore-latest.osrm
      "

networks:
  default:
    driver: bridge