services:
  osrm:
    image: osrm/osrm-backend
    volumes:
      - ~/singapore-osm:/data
      - ./profiles:/profiles
    networks:
      - default
    ports:
      - 6000:5000
    restart: unless-stopped
    command: >
      bash -c "
      osrm-extract -p /profiles/foot.lua /data/singapore-latest.osm.pbf && 
      osrm-partition /data/singapore-latest.osrm && 
      osrm-customize /data/singapore-latest.osrm && 
      osrm-routed \
      --algorithm mld \
      --max-matching-size 20000 \
      --max-viaroute-size 20000 \
      --max-trip-size 20000 \
      --max-table-size 20000 \
      /data/singapore-latest.osrm
      "

  overpass-api:
    image: wiktorn/overpass-api
    volumes:
      - ~/singapore-osm:/data
    ports:
      - "8000:80"
    environment:
      - OVERPASS_META=yes
      - OVERPASS_MODE=init
      - OVERPASS_PLANET_URL=file:///data/singapore-latest.osm.bz2
      - OVERPASS_RULES_LOAD=10
      - OVERPASS_ALLOW_DUPLICATE_QUERIES=yes
    networks:
      - default
    restart: unless-stopped

networks:
  default:
    driver: bridge